### ISSUE TITLE
How I can use even DataStoreReadFrom?

### ISSUE THREAD

**Issue by vajarkov** [sankarr/Nmodbus#2]
I wrote program with multiple slaves and I want to use event DataStoreReadFrom, but I don't  know what

**Comment by sankarr** [comment]
m_data_1.DataStoreReadFrom += m_data_1_DataStoreReadFrom;     



void m_data_1_DataStoreReadFrom(object sender, DataStoreEventArgs e)
        {
            int start  = e.StartAddress ;
            if(e.ModbusDataType==ModbusDataType.HoldingRegister){
               // do something
            }
        }

**Comment by sankarr** [comment]
This is how the event is raised:

dataStore.DataStoreReadFrom.Raise(dataStore, DataStoreEventArgs.CreateDataStoreEventArgs(startAddress, dataSource.ModbusDataType, result));

**Comment by vajarkov** [comment]
m_data_1 is DataStore from first of two slave in my program?

**Comment by sankarr** [comment]
The event is thrown by the data store. You map an address to a datastore.

 map.Add(unitID1, data1);
 map.Add(unitID2, data1);

Suppose you mapped two addresses to the same datastore then when either address is used the datastore would raise the event.

In the case you used two different data stores:
 map.Add(unitID1, data1);
 map.Add(unitID2, data2);
You need to attach a handler to each datastore.

**Comment by vajarkov** [comment]
I create DataStore dynamicly and I don't know how dynamicly create event for own slaveId

public void CreateDataStore(byte slaveId, ushort[] AWAUS, ushort[] BWAUS)
        {
            #region Создание хранилища

            // Создаем хранилище данных для ModbusSlave
            // DataStore dataStore = DataStoreFactory.CreateDefaultDataStore();
            // Устанавливаем стартовый адрес для аналоговых значений
            int nAddressMB = 1;

            #endregion

            #region Запись данных в хранилище

            // Записываем аналоговые значения
            if (!mapSlavesData.ContainsKey(slaveId))
            {
                try
                {
                    mapSlavesData.Add(slaveId, DataStoreFactory.CreateDefaultDataStore());
                }
                catch (Exception ex)
                {
                    // Если ошибка пишем в журнал
                    EventLog eventLog = new EventLog();
                    if (!EventLog.SourceExists("ModbusRTUService"))
                    {
                        EventLog.CreateEventSource("ModbusRTUService", "ModbusRTUService");
                    }
                    eventLog.Source = "ModbusRTUService";
                    eventLog.WriteEntry("Modbus Slave : " + slaveId.ToString() + "\n" + ex.Message, EventLogEntryType.Error);

                }
            }
            try
            {

                // Записыванем аналоговые значения
                foreach (ushort item in AWAUS)
                {
                    mapSlavesData[slaveId].HoldingRegisters[nAddressMB] = item;
                    nAddressMB++;
                }

                // Смещаем адрес для дискретных значений
                nAddressMB = 1001;

                // Записываем дискретные значения
                foreach (ushort item in BWAUS)
                {
                    mapSlavesData[slaveId].HoldingRegisters[nAddressMB] = item;
                    nAddressMB++;
                }
            }
                catch (Exception ex)
            {
                // Если ошибка пишем в журнал
                EventLog eventLog = new EventLog();
                if (!EventLog.SourceExists("ModbusRTUService"))
                {
                    EventLog.CreateEventSource("ModbusRTUService", "ModbusRTUService");
                }
                eventLog.Source = "ModbusRTUService";
                eventLog.WriteEntry("Modbus Slave : " + slaveId.ToString() + "\n" + ex.Message, EventLogEntryType.Error);
            }
            

            #endregion

        }

**Comment by vajarkov** [comment]
Or pass my event slaveId

**Comment by vajarkov** [comment]
I create anonymous function on event with code in previous message, but my HoldingRegisters not update

**Comment by sankarr** [comment]
public void CreateDataStore(byte slaveId, ushort[] AWAUS, ushort[] BWAUS)
{
#region Создание хранилища

        // Создаем хранилище данных для ModbusSlave
        // DataStore dataStore = DataStoreFactory.CreateDefaultDataStore();
        // Устанавливаем стартовый адрес для аналоговых значений
        int nAddressMB = 1;

        #endregion

        #region Запись данных в хранилище

        // Записываем аналоговые значения
        if (!mapSlavesData.ContainsKey(slaveId))
        {
            try
            {
               //do this:
               var ds = DataStoreFactory.CreateDefaultDataStore();
               ds.DataStoreReadFrom += m_data_1_DataStoreReadFrom;

                mapSlavesData.Add(slaveId, ds);
            }
            catch (Exception ex)
            {
                // Если ошибка пишем в журнал
                EventLog eventLog = new EventLog();
                if (!EventLog.SourceExists("ModbusRTUService"))
                {
                    EventLog.CreateEventSource("ModbusRTUService", "ModbusRTUService");
                }
                eventLog.Source = "ModbusRTUService";
                eventLog.WriteEntry("Modbus Slave : " + slaveId.ToString() + "\n" + ex.Message, EventLogEntryType.Error);

            }
        }
        try
        {

            // Записыванем аналоговые значения
            foreach (ushort item in AWAUS)
            {
                mapSlavesData[slaveId].HoldingRegisters[nAddressMB] = item;
                nAddressMB++;
            }

            // Смещаем адрес для дискретных значений
            nAddressMB = 1001;

            // Записываем дискретные значения
            foreach (ushort item in BWAUS)
            {
                mapSlavesData[slaveId].HoldingRegisters[nAddressMB] = item;
                nAddressMB++;
            }
        }
            catch (Exception ex)
        {
            // Если ошибка пишем в журнал
            EventLog eventLog = new EventLog();
            if (!EventLog.SourceExists("ModbusRTUService"))
            {
                EventLog.CreateEventSource("ModbusRTUService", "ModbusRTUService");
            }
            eventLog.Source = "ModbusRTUService";
            eventLog.WriteEntry("Modbus Slave : " + slaveId.ToString() + "\n" + ex.Message, EventLogEntryType.Error);
        }


        #endregion

    }

**Comment by vajarkov** [comment]
Thanks, not work. You don't want help me)))

**Comment by vajarkov** [comment]
public void CreateDataStore(byte slaveId, ushort[] AWAUS, ushort[] BWAUS)
{
#region Создание хранилища

        // Создаем хранилище данных для ModbusSlave
        // DataStore dataStore = DataStoreFactory.CreateDefaultDataStore();
        // Устанавливаем стартовый адрес для аналоговых значений
        int nAddressMB = 1;

        #endregion

        #region Запись данных в хранилище

        // Записываем аналоговые значения
        if (!mapSlavesData.ContainsKey(slaveId))
        {
            try
            {
                mapSlavesData.Add(slaveId, DataStoreFactory.CreateDefaultDataStore());
                mapSlaveData[slaveId].DataStoreReadFrom += (obj, e) =>{

        try
        {

            // Записыванем аналоговые значения
            foreach (ushort item in AWAUS)
            {
                mapSlavesData[slaveId].HoldingRegisters[nAddressMB] = item;
                nAddressMB++;
            }

            // Смещаем адрес для дискретных значений
            nAddressMB = 1001;

            // Записываем дискретные значения
            foreach (ushort item in BWAUS)
            {
                mapSlavesData[slaveId].HoldingRegisters[nAddressMB] = item;
                nAddressMB++;
            }
        }
            catch (Exception ex)
        {
            // Если ошибка пишем в журнал
            EventLog eventLog = new EventLog();
            if (!EventLog.SourceExists("ModbusRTUService"))
            {
                EventLog.CreateEventSource("ModbusRTUService", "ModbusRTUService");
            }
            eventLog.Source = "ModbusRTUService";
            eventLog.WriteEntry("Modbus Slave : " + slaveId.ToString() + "\n" + ex.Message, EventLogEntryType.Error);
        }




}
            }
            catch (Exception ex)
            {
                // Если ошибка пишем в журнал
                EventLog eventLog = new EventLog();
                if (!EventLog.SourceExists("ModbusRTUService"))
                {
                    EventLog.CreateEventSource("ModbusRTUService", "ModbusRTUService");
                }
                eventLog.Source = "ModbusRTUService";
                eventLog.WriteEntry("Modbus Slave : " + slaveId.ToString() + "\n" + ex.Message, EventLogEntryType.Error);

            }
        }
        #endregion

    }

**Comment by vajarkov** [comment]
Event is work, but dont't update DataStore. Before I create ModbusRTU and onTimer after 1 minute destroy Modbus and create again. This cycle work in my Windows Service while I stop this service. And now I want don't destroy Modbus and write new value in Modbus on event after read. Can I this cycle or not?

**Comment by vajarkov** [comment]
I find this example
https://code.google.com/p/nmodbus/issues/attachmentText?id=60&aid=600000000&name=TcpSlave.cs&token=ABZ6GAfzyePRW7SlhJwNLVEpPGQaK_pLyA%3A1438048348567
